# fly.toml file generated for tmai-management-dashboard on 2024-02-02T05:35:06+01:00

app = "tmai-management-dashboard"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "jnb"
processes = []

[build]
  [build.args]
    NEXT_PUBLIC_EXAMPLE = "Value goes here"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
